import { NEXT_PUBLIC_API_BASE_URL } from "@utils/constant";

export const queryConfig = {
	refetchOnWindowFocus: false,
};
export const apiEndpoint = {
	base: NEXT_PUBLIC_API_BASE_URL,
	register: `${NEXT_PUBLIC_API_BASE_URL}/register`,
	login: `${NEXT_PUBLIC_API_BASE_URL}/login`,
	logout: `${NEXT_PUBLIC_API_BASE_URL}/logout`,
	slider: `${NEXT_PUBLIC_API_BASE_URL}/sliders`,
	product: `${NEXT_PUBLIC_API_BASE_URL}/products`,
	categories: `${NEXT_PUBLIC_API_BASE_URL}/categories`,
	productCollection: `${NEXT_PUBLIC_API_BASE_URL}/product-collection`,
	aboutUs: `${NEXT_PUBLIC_API_BASE_URL}/about_us`,
	privacyPolicy: `${NEXT_PUBLIC_API_BASE_URL}/privacy_policy`,
	exchangePolicy: `${NEXT_PUBLIC_API_BASE_URL}/exchange_policy`,
	lookBook: `${NEXT_PUBLIC_API_BASE_URL}/look_book`,
	sizeGuide: `${NEXT_PUBLIC_API_BASE_URL}/size_guide`,
	partner: `${NEXT_PUBLIC_API_BASE_URL}/partner`,
	store: `${NEXT_PUBLIC_API_BASE_URL}/store`,
	cart: `${NEXT_PUBLIC_API_BASE_URL}/cart`,
	menu: `${NEXT_PUBLIC_API_BASE_URL}/menu`,
	removeCart: `${NEXT_PUBLIC_API_BASE_URL}/removeCart`,
	categoryProduct: `${NEXT_PUBLIC_API_BASE_URL}/categoryProduct`,
	address: `${NEXT_PUBLIC_API_BASE_URL}/address`,
	review: `${NEXT_PUBLIC_API_BASE_URL}/review`,
	wishlist: `${NEXT_PUBLIC_API_BASE_URL}/wishlist`,
	removeWishlist: `${NEXT_PUBLIC_API_BASE_URL}/removeWishlist`,
	updateProfile: `${NEXT_PUBLIC_API_BASE_URL}/updateProfile`,
	changePassword: `${NEXT_PUBLIC_API_BASE_URL}/changePassword`,
	verifyProfile: `${NEXT_PUBLIC_API_BASE_URL}/verifyProfile`,
	checkout: `${NEXT_PUBLIC_API_BASE_URL}/checkout`,
	esewaSuccess: `${NEXT_PUBLIC_API_BASE_URL}/esewa/success`,
	khaltiInit: `${NEXT_PUBLIC_API_BASE_URL}/khalti/init-transaction`,
	khaltiConfirm: `${NEXT_PUBLIC_API_BASE_URL}/khalti/confirm-transaction`,
	khaltiSuccess: `${NEXT_PUBLIC_API_BASE_URL}/khalti/success`,
	checkoutComplete: `${NEXT_PUBLIC_API_BASE_URL}/checkout-complete`,
	user: `${NEXT_PUBLIC_API_BASE_URL}/user`,
	contactUs: `${NEXT_PUBLIC_API_BASE_URL}/contact_form`,
	myOrder: `${NEXT_PUBLIC_API_BASE_URL}/my_order`,
	getOTP: `${NEXT_PUBLIC_API_BASE_URL}/getOtp`,
	newsletter: `${NEXT_PUBLIC_API_BASE_URL}/newsletter`,
	validate_coupon: `${NEXT_PUBLIC_API_BASE_URL}/validate_coupon`,
	search: `${NEXT_PUBLIC_API_BASE_URL}/search`,
	blog: `${NEXT_PUBLIC_API_BASE_URL}/blog`,
	getConfiguration: `${NEXT_PUBLIC_API_BASE_URL}/configuration`,
	attributes: `${NEXT_PUBLIC_API_BASE_URL}/attributes`,
	siblingCategory: `${NEXT_PUBLIC_API_BASE_URL}/descendant-categories`,
	pages: `${NEXT_PUBLIC_API_BASE_URL}/page`,
	socialLogin: `${NEXT_PUBLIC_API_BASE_URL}/social-login`,
	quotations: `${NEXT_PUBLIC_API_BASE_URL}/quotations`,
};


